### ISSUE TITLE
Reconcile RDF type for IIIF vs. SC

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/annotations2triannon#4]
IIIF => http://iiif.io/api/presentation/2.0/
SC => http://iiif.io/model/shared-canvas/1.0/index.html

The IIIF presentation 2.0 is an evolution of the SC.  Some IIIF documents may contain SC entities.

A IIIF collection can list manifests with rdf type 'IIIFManifest', but when the rdf is loaded for the manifest, it may declare that it is of rdf type 'SCManifest'.  These rdf types may be effectively 'owl:sameAs', so this might be a moot point.  However, if these vocabularies entail significantly different meaning, it may be important to reconcile the differences.  The requirements for such reconciliation are to be determined.

It should be noted here that the IIIFNavigator relies on the collection to identify the manifest rdf type.  Likewise, it relies on the manifest to identify the rdf type of annotation lists.  There are methods within the Manifest and AnnotationList classes to determine whether they are IIIF or SC types.

**Comment by azaroth42** [comment]
iiif:Manifest owl:sameAs sc:Manifest is definitely a valid assertion.

**Comment by dazza-codes** [comment]
Example code to identify and resolve IIIF vs. SC manifests:

```
# Explore the collection to resolve IIIF and Shared Canvas (SC) manifests.
iiif_manifests = []
sc_manifests = []

# Examine IIIF manifests in the collection
iiif_manifests.push(* iiif_navigator.iiif_manifests)
# A IIIF collection might contain a IIIF manifest that itself
# could be typed as an SC manifest.
tmp = iiif_manifests.select {|m| m if m.sc_manifest? }
tmp.each do |m|
  sc_manifests << Annotations2triannon::SharedCanvasManifest.new(m.iri.to_s)
end
iiif_manifests = iiif_manifests.select {|m| m if m.iiif_manifest? }

# Examine SC manifests in the collection
sc_manifests.push(* iiif_navigator.sc_manifests)
# A IIIF collection might contain an SC manifest that itself
# could be typed as a IIIF manifest.
iiif_manifests.push(* sc_manifests.select {|m| m if m.iiif_manifest? } )
tmp = sc_manifests.select {|m| m if m.iiif_manifest? }
tmp.each do |m|
  iiif_manifests << Annotations2triannon::IIIFManifest.new(m.iri.to_s)
end
sc_manifests = sc_manifests.select {|m| m if m.sc_manifest? }

# The collection should be now resolved into IIIF and SC manifests, 
# based on the rdf type of the manifest (not the collection).
```

**Comment by dazza-codes** [comment]
The current solution to this problem was to create a base class for manifests that combines IIIF and SC manifests.  There are two subclasses, which filter the manifests specifically for IIIF or SC manifests (these are less useful than the base class because of the owl:sameAs relation between IIIF and SC manifests, but they are available in case it helps diagnostics or stats on parsing data).
